[source]
type = "N2C"
socket_path = "/home/relay/cardano-my-node/db/socket"
min_depth = 6

[intersect]
type = "Point"
value = [133071753, "ca0e667649146da8141fcb92a92ddccb5db841c6cf9a2b534f0bf00e92dc3185"]

[cursor]
type = "File"
path = "/home/relay/fortuna-stream/oura.cursor"

[[filters]]
type = "SplitBlock"

[[filters]]
type = "ParseCbor"

[[filters]]
type = "Select"
skip_uncertain = true
predicate = "asset1up3fehe0dwpuj4awgcuvl0348vnsexd573fjgq"

[sink]
type = "WebHook"
url = "http://127.0.0.1:30513/api/events"