[source]
type = "N2N"
peers = ["192.168.0.110:6000"]
min_depth = 6

[intersect]
type = "Point"
value = [133071753, "ca0e667649146da8141fcb92a92ddccb5db841c6cf9a2b534f0bf00e92dc3185"]

[cursor]
type = "File"
path = "oura.cursor"

[[filters]]
type = "SplitBlock"

[[filters]]
type = "ParseCbor"

[[filters]]
type = "Select"
skip_uncertain = true

[filters.predicate]
any = [
    "asset1up3fehe0dwpuj4awgcuvl0348vnsexd573fjgq",                     # TUNA v2 asset
    "addr1w8ax5k9mutg07p2ngscu3chsauktmstq92z9de938j8nqacprc9mw"        # SundaeSwap V3 order script (see dexes.json)
]

[sink]
type = "WebHook"
url = "http://127.0.0.1:30513/api/events"